### ISSUE TITLE
如果第二个pageview也有小tab呢？

### ISSUE THREAD

**Issue by jacobfung** [yongfengnice/flutter_nest_page_view#1]
两个pageview下分别有不同的tab的嵌套滚动

**Comment by yongfengnice** [comment]
你看一下链接的演示效果哈，第二个其他也可以当作是tab吧？添加title就可以了？？

**Comment by jacobfung** [comment]
> 你看一下链接的演示效果哈，第二个其他也可以当作是tab吧？添加title就可以了？？

演示的demo只是第一个pageview下有它的tabbar，现在我这边的情况是第二个页面也是有tabbar，这个时候我这边用下来的话第二个pageview是不能通过滑动回到第一个

**Comment by yongfengnice** [comment]
demo里的第二个是PageView，你的需求第二个是TabbarView这样？你看一下能不能改造一下utils里的处理，或者我这两天看看

**Comment by jacobfung** [comment]
我是flutter初学者，所以不是特别熟悉。我现在这边是一个 pageController，两个tabController，现在的话效果是滑到第二个页面后之后不能滑回来，如这样 https://665756.ma3you.cn/static/tourguide/content_show/index.html?v=20220520#/pages/article_view/article_view?article_id=b6dk8yR ， 我也可以把代码发给你，感谢相助。

**Comment by yongfengnice** [comment]
更新了，添加了tarbarview嵌套，希望能帮到你哈，对你有用可以star一下

**Comment by jacobfung** [comment]
> 更新了，添加了tarbarview嵌套，希望能帮到你哈，对你有用可以star一下

通过其他开源的包解决了哈，但是也非常感谢，已star

**Comment by Moyout** [comment]
> 可以帮到你了，希望能帮到你哈

没有注释很看难懂😢，作者可以写上注释，希望你不要不识抬举😾
