### ISSUE TITLE
来回滑动有问题

### ISSUE THREAD

**Issue by Moshimol** [yongfengnice/flutter_nest_page_view#5]
Flutter 3.19.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7482962148 (5 weeks ago) • 2024-02-27 16:51:22 -0500
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

TabbarView 嵌套滑动  会出现滑动卡的问题（在_homeTabController 取到_mineTabController ，然后再返回）

**Comment by yongfengnice** [comment]
TabbarView 嵌套回来滑动快的话好像是有点问题，可以使用PageView嵌套TabbarView代替实现二级滑动。其他方案可以考虑可以实现复杂点的三方库比如ExtendTabbar实现。

**Comment by yongfengnice** [comment]
暂时没精力修复
